name: Build

on: [push, pull_request]

jobs:
  test:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]

    steps:
      - uses: actions/checkout@v4
      # Setup .npmrc file to publish to npm
      - uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: npm
          registry-url: 'https://registry.npmjs.org'
        env:
            NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      - run: npm ci
      - run: npm run check-build
      - name: "Check file existence"
        uses: andstor/file-existence-action@v2
        with:
          files: "build.file"
      - name: Build
        if: steps.check_files.outputs.files_exists == 'true'
        run: echo All files exists!
        run: npm run prebuild -- -u ${{ secrets.REPO_TOKEN }}
        run: npm publish --access=public
      - name: No Build Needed
        if: steps.check_files.outputs.files_exists == 'false'
        run: echo No need to build
        