name: Test

on: [push, pull_request]

jobs:
  test:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]

    steps:
      - uses: actions/checkout@v4
      # Setup .npmrc file to publish to npm
      - uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: npm
          registry-url: 'https://registry.npmjs.org'
        env:
            NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
            UPLOAD_TOKEN: ${{ secrets.REPO_TOKEN }}
      - run: npm ci
      - run: npm run github-build
        